In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame({
 "column1": [1, 2, 3],
 "column2": [4, 5, 6],
 'columns3': "Sunasara Haidarali Hasanali".split()

})

In [4]:
"Sunasara Haidarali Hasanali".split()

['Sunasara', 'Haidarali', 'Hasanali']

In [5]:
df

column1  column2   columns3
0        1        4   Sunasara
1        2        5  Haidarali
2        3        6   Hasanali

In [6]:
df['column4'] = df['column1']**2
df

column1  column2   columns3  column4
0        1        4   Sunasara        1
1        2        5  Haidarali        4
2        3        6   Hasanali        9

In [7]:
df['column5'] = df['columns3'].str[0]
df

column1  column2   columns3  column4 column5
0        1        4   Sunasara        1       S
1        2        5  Haidarali        4       H
2        3        6   Hasanali        9       H

In [10]:
df['columns6'] = [ch if ch == "S" else 'Z' for ch in df['column5']]
# 
df



column1  column2   columns3  column4 column5 columns6
0        1        4   Sunasara        1       S        S
1        2        5  Haidarali        4       H        Z
2        3        6   Hasanali        9       H        Z

In [11]:
#Let's talk about apply function in pandas
#The apply function is used to apply a function along the axis of the DataFrame.
#It can be used to apply a function to each row or each column.
#For example, you can use apply to calculate the sum of each row or each column.
#we have define function first
def test(z):
    return z**2

# Now we can use the apply function to apply our test function to a DataFrame column
df['column7'] = df['column1'].apply(test) #It's applied to each element in the column
df

column1  column2   columns3  column4 column5 columns6  column7
0        1        4   Sunasara        1       S        S        1
1        2        5  Haidarali        4       H        Z        4
2        3        6   Hasanali        9       H        Z        9

In [20]:
#Another Example with condition
def test1(x):
    if x == 'S':
        return 'S'
    else:
        return 'Z'
df['columns8'] = df['column5'].apply(test1)

df

#Another Way using Lambda
df['columns9'] = df['column5'].apply(lambda x:'S' if x== 'S' else 'Z')
df

column1  column2   columns3  column4 column5 columns6  column7 columns8  \
0        1        4   Sunasara        1       S        S        1        S   
1        2        5  Haidarali        4       H        Z        4        Z   
2        3        6   Hasanali        9       H        Z        9        Z   

  columns9  
0        S  
1        Z  
2        Z

In [23]:
#Another using inbuild function in apply function itself
df['column10'] = df['columns3'].apply(len)
df

column1  column2   columns3  column4 column5 columns6  column7 columns8  \
0        1        4   Sunasara        1       S        S        1        S   
1        2        5  Haidarali        4       H        Z        4        Z   
2        3        6   Hasanali        9       H        Z        9        Z   

  columns9  column10  
0        S         8  
1        Z         9  
2        Z         8

In [24]:
#Another way using math library
#import math
import math
df['column11'] = df['column2'].apply(math.log)
df

column1  column2   columns3  column4 column5 columns6  column7 columns8  \
0        1        4   Sunasara        1       S        S        1        S   
1        2        5  Haidarali        4       H        Z        4        Z   
2        3        6   Hasanali        9       H        Z        9        Z   

  columns9  column10  column11  
0        S         8  1.386294  
1        Z         9  1.609438  
2        Z         8  1.791759

In [1]:
#Let's understand about numpy library
#numpy is a library
#It is used for numerical operations in Python.
#It provides support for arrays, matrices, and many mathematical functions.
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [3]:
type(arr1)

numpy.ndarray

In [5]:
arr1 = np.array([1, 2, 3, 4, 5.0])
print(arr1)
type(arr1)

[1. 2. 3. 4. 5.]


numpy.ndarray

In [6]:
#2-d array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
type(arr2)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

In [9]:
#Accessing elements
print(arr1[0])  # Accessing the first element
print(arr2[1][2])  # Accessing the element at row 1, column 2
#another way
print(arr2[1, 2])  # Accessing the element at row 1, column 2

1.0
6
6


In [10]:
#ndim
print(arr1.ndim)
print(arr2.ndim)


1
2


In [37]:
#Assign ndim number of dimension
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]],ndmin=4)
arr2.shape
arr2

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [44]:
# arr2 has shape (1, 3, 3, 3), so valid indices for axis 0 are [0]
# Let's access a valid element, for example:
arr2[0][0][2][2]  # This will access the element at [0][0][2][2]
print(arr2[0][0][2][2])
#another way
arr2[0, 0, 2, 2]  # This will access the element at [0][0][2][2]
print(arr2[0, 0, 2, 2])

9
9


In [45]:
np.asarray([1, 2, 3, 4, 5.0])  # This will create a numpy array with float type
# what is different
# The input list contains a float, so the resulting array will have a float data type.


array([1., 2., 3., 4., 5.])

In [ ]:
np.asanyarray([1, 2, 3, 4, 5])
# what is asanyarray
# asanyarray is a function in NumPy that converts the input to an ndarray, but it will not copy the data if the input is already an ndarray.
# asanyarray is useful when you want to ensure that the input is treated as an ndarray, but you don't want to create a new copy if it's already an ndarray.
# It is similar to asarray, but asanyarray will also accept subclasses of ndarray.
# For example:
# class MyArray(np.ndarray):
#     pass
# arr = MyArray([1, 2, 3])
# result = np.asanyarray(arr)
# The result will be an ndarray, and it will not create a copy of the data.

In [50]:
#Let's understand of matrix using asmatrix() function
# The asmatrix() function is used to create a matrix from an array-like structure.
# It is similar to the np.array() function, but it always returns a matrix (2D array).
# For example:
matrix = np.asmatrix([1,2,3,4,5])
matrix

matrix([[1, 2, 3, 4, 5]])

In [53]:
a = [1,2,3,4,5]
np.asanyarray(a)

array([1, 2, 3, 4, 5])

In [54]:
np.asmatrix(a)

matrix([[1, 2, 3, 4, 5]])

In [51]:
np.asanyarray(np.asmatrix([1, 2, 3, 4, 5]))

matrix([[1, 2, 3, 4, 5]])

In [ ]:
import numpy as np
# Let's understand about fromfunction
# The `fromfunction` method in NumPy allows you to create an array by executing a function over each coordinate of the array.
# This can be particularly useful for generating arrays with specific patterns or values.
# Let's see an example of how to use `fromfunction`.
np.fromfunction(lambda i,j: i==j,(3,3))



array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [4]:
# An example of using fromfunction
np.fromfunction(lambda i,j:i+j,(3,3),dtype=int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [6]:
np.fromfunction(lambda i,j,z: i+j+z, (3, 3, 2), dtype=int)

array([[[0, 1],
        [1, 2],
        [2, 3]],

       [[1, 2],
        [2, 3],
        [3, 4]],

       [[2, 3],
        [3, 4],
        [4, 5]]])

In [7]:
np.fromfunction(lambda i,j,z: i*j*z,(4,3,2),dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [8]:
np.fromfunction(lambda i,j,z,w: i*j*z*w,(4,3,2,5),dtype=int)

array([[[[ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0]],

        [[ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0]],

        [[ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0]]],


       [[[ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0]],

        [[ 0,  0,  0,  0,  0],
         [ 0,  1,  2,  3,  4]],

        [[ 0,  0,  0,  0,  0],
         [ 0,  2,  4,  6,  8]]],


       [[[ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0]],

        [[ 0,  0,  0,  0,  0],
         [ 0,  2,  4,  6,  8]],

        [[ 0,  0,  0,  0,  0],
         [ 0,  4,  8, 12, 16]]],


       [[[ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0]],

        [[ 0,  0,  0,  0,  0],
         [ 0,  3,  6,  9, 12]],

        [[ 0,  0,  0,  0,  0],
         [ 0,  6, 12, 18, 24]]]])

In [50]:
ar1 = np.fromfunction(lambda i,j,z: i*j*z,(4,3,2),dtype=int)

In [51]:
ar1.reshape(12, 2)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 2],
       [0, 0],
       [0, 2],
       [0, 4],
       [0, 0],
       [0, 3],
       [0, 6]])

In [13]:
ar1.ndim

3

In [14]:
ar1.size

24

In [15]:
ar1.shape

(4, 3, 2)

In [16]:
ar1.dtype

dtype('int64')

In [ ]:
#convert ar1 TO dataframe
import pandas as pd
pd.DataFrame(ar1)
#it will give error ValueError: Length of passed values is 24, index implies 12
#because the shape of the array is (4, 3, 2) and it needs to be 2D

ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [22]:
ar1 = np.fromfunction(lambda i,j:i*j,(400,100),dtype=int)
#Now convert to dataframe
pd.DataFrame(ar1)

0    1    2     3     4     5     6     7     8     9   ...     90  \
0     0    0    0     0     0     0     0     0     0     0  ...      0   
1     0    1    2     3     4     5     6     7     8     9  ...     90   
2     0    2    4     6     8    10    12    14    16    18  ...    180   
3     0    3    6     9    12    15    18    21    24    27  ...    270   
4     0    4    8    12    16    20    24    28    32    36  ...    360   
..   ..  ...  ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
395   0  395  790  1185  1580  1975  2370  2765  3160  3555  ...  35550   
396   0  396  792  1188  1584  1980  2376  2772  3168  3564  ...  35640   
397   0  397  794  1191  1588  1985  2382  2779  3176  3573  ...  35730   
398   0  398  796  1194  1592  1990  2388  2786  3184  3582  ...  35820   
399   0  399  798  1197  1596  1995  2394  2793  3192  3591  ...  35910   

        91     92     93     94     95     96     97     98     99  
0        0      0      0      0      0      0      0      0      0  
1       91     92     93     94     95     96     97     98     99  
2      182    184    186    188    190    192    194    196    198  
3      273    276    279    282    285    288    291    294    297  
4      364    368    372    376    380    384    388    392    396  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
395  35945  36340  36735  37130  37525  37920  38315  38710  39105  
396  36036  36432  36828  37224  37620  38016  38412  38808  39204  
397  36127  36524  36921  37318  37715  38112  38509  38906  39303  
398  36218  36616  37014  37412  37810  38208  38606  39004  39402  
399  36309  36708  37107  37506  37905  38304  38703  39102  39501  

[400 rows x 100 columns]

In [23]:
np.random.rand(3, 2)  # Generates a 3x2 array of random floats in the range [0.0, 1.0)

array([[0.38005967, 0.67933152],
       [0.7842186 , 0.13101146],
       [0.497072  , 0.97956398]])

In [41]:
np.random.randint(0, 10,(3,3))  # Generates a 3x2 array of random integers in the range [0, 10)

array([[9, 0, 0],
       [8, 1, 3],
       [7, 9, 9]], dtype=int32)

In [45]:
data = np.random.randn(4,5)# Generates a 4x5 array of random floats from the standard normal distribution (mean=0, std=1)

In [46]:
pd.DataFrame(data)  # Convert the random data to a DataFrame for better visualization

0         1         2         3         4
0  1.084578 -0.126943  1.678653  0.660532 -0.698940
1  0.866215  0.307960 -0.554252  1.437444  0.453507
2 -0.181170  1.182748  0.172713 -0.311843 -0.647082
3 -0.590122 -0.225804  0.127556 -0.170842 -1.157964

In [57]:
#reshape
data = ar1.reshape(3, 4,-1)  # Reshape the array to have 12 rows and 2 columns
data

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 1],
        [0, 2],
        [0, 0],
        [0, 2]],

       [[0, 4],
        [0, 0],
        [0, 3],
        [0, 6]]])

In [62]:
a = np.arange(4,10,.5)

In [63]:
a

array([4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [64]:
a[1:4]

array([4.5, 5. , 5.5])

In [65]:
array_1 = np.random.rand(4, 5)
array_1

array([[0.74527397, 0.35604102, 0.33344253, 0.937696  , 0.38574033],
       [0.79246398, 0.93163076, 0.46918734, 0.70475947, 0.99724074],
       [0.17129579, 0.36200287, 0.40615522, 0.43814631, 0.46675299],
       [0.65211051, 0.71542639, 0.79214979, 0.48962275, 0.83744211]])

In [67]:
array_1[array_1 > 0.5]

array([0.74527397, 0.937696  , 0.79246398, 0.93163076, 0.70475947,
       0.99724074, 0.65211051, 0.71542639, 0.79214979, 0.83744211])

In [69]:
array_1

array([[0.74527397, 0.35604102, 0.33344253, 0.937696  , 0.38574033],
       [0.79246398, 0.93163076, 0.46918734, 0.70475947, 0.99724074],
       [0.17129579, 0.36200287, 0.40615522, 0.43814631, 0.46675299],
       [0.65211051, 0.71542639, 0.79214979, 0.48962275, 0.83744211]])

In [75]:
array_1[[1,2],3]

array([0.70475947, 0.43814631])

In [76]:
array_2 = np.random.rand(8,5)

In [77]:
array_2

array([[0.85217392, 0.29498651, 0.88679566, 0.62074449, 0.97937267],
       [0.99038475, 0.89660903, 0.32412973, 0.86252973, 0.89781811],
       [0.99579932, 0.263622  , 0.267868  , 0.26122226, 0.84657354],
       [0.7058405 , 0.82508483, 0.07537703, 0.08963022, 0.36961532],
       [0.61683973, 0.33014343, 0.85030653, 0.61119854, 0.78233994],
       [0.98872748, 0.8527942 , 0.34133361, 0.19464864, 0.66932524],
       [0.59291151, 0.48103653, 0.47752252, 0.33677296, 0.76893601],
       [0.09852531, 0.6716557 , 0.67748747, 0.32914582, 0.01638584]])

In [78]:
array_2[1:7,0:3]

array([[0.99038475, 0.89660903, 0.32412973],
       [0.99579932, 0.263622  , 0.267868  ],
       [0.7058405 , 0.82508483, 0.07537703],
       [0.61683973, 0.33014343, 0.85030653],
       [0.98872748, 0.8527942 , 0.34133361],
       [0.59291151, 0.48103653, 0.47752252]])

In [80]:
array_2[0][0] = 200
array_2

array([[2.00000000e+02, 2.94986510e-01, 8.86795660e-01, 6.20744486e-01,
        9.79372671e-01],
       [9.90384745e-01, 8.96609027e-01, 3.24129734e-01, 8.62529729e-01,
        8.97818115e-01],
       [9.95799322e-01, 2.63622001e-01, 2.67868004e-01, 2.61222262e-01,
        8.46573538e-01],
       [7.05840500e-01, 8.25084833e-01, 7.53770280e-02, 8.96302197e-02,
        3.69615323e-01],
       [6.16839734e-01, 3.30143425e-01, 8.50306531e-01, 6.11198536e-01,
        7.82339943e-01],
       [9.88727483e-01, 8.52794203e-01, 3.41333608e-01, 1.94648642e-01,
        6.69325242e-01],
       [5.92911509e-01, 4.81036527e-01, 4.77522515e-01, 3.36772961e-01,
        7.68936008e-01],
       [9.85253095e-02, 6.71655704e-01, 6.77487472e-01, 3.29145816e-01,
        1.63858354e-02]])

In [81]:
a = np.array([[1,2] ,[3,4]])
b = np.array([[2,3] , [4,5]])

In [82]:
a

array([[1, 2],
       [3, 4]])

In [83]:
b

array([[2, 3],
       [4, 5]])

In [84]:
a*b

array([[ 2,  6],
       [12, 20]])

In [86]:
#matrix multiplication
c = np.matmul(a, b)
c

array([[10, 13],
       [22, 29]])

In [87]:
#another way
c = a @ b
c

array([[10, 13],
       [22, 29]])

In [89]:
c/0

C:\Users\haida\AppData\Local\Temp\ipykernel_16992\97081324.py:1: RuntimeWarning: divide by zero encountered in divide
  c/0


array([[inf, inf],
       [inf, inf]])