In [1]:
import numpy as np

In [2]:
l = [1,2,4,45,5,6,6]
arr = np.array(l)
arr

array([ 1,  2,  4, 45,  5,  6,  6])

# NumPy Methods
NumPy provides a wide range of methods for performing operations on arrays.
These methods allow for efficient manipulation and computation on large datasets.

Some commonly used NumPy methods include:

- **`np.array()`**: Create a NumPy array.
  ```python
  arr = np.array([1, 2, 3])
  print(arr)
  # Output: [1 2 3]
  ```

- **`np.zeros()`**: Create an array filled with zeros.
  ```python
  zeros = np.zeros((2, 3))
  print(zeros)
  # Output: [[0. 0. 0.]
  #          [0. 0. 0.]]
  ```

- **`np.ones()`**: Create an array filled with ones.
  ```python
  ones = np.ones((2, 3))
  print(ones)
  # Output: [[1. 1. 1.]
  #          [1. 1. 1.]]
  ```

- **`np.arange()`**: Create an array with a range of values.
  ```python
  arr = np.arange(0, 10, 2)
  print(arr)
  # Output: [0 2 4 6 8]
  ```

- **`np.linspace()`**: Create an array with evenly spaced values.
  ```python
  arr = np.linspace(0, 1, 5)
  print(arr)
  # Output: [0.   0.25 0.5  0.75 1.  ]
  ```

- **`np.reshape()`**: Change the shape of an array.
  ```python
  arr = np.arange(6)
  reshaped = arr.reshape((2, 3))
  print(reshaped)
  # Output: [[0 1 2]
  #          [3 4 5]]
  ```

- **`np.concatenate()`**: Join two or more arrays.
  ```python
  a = np.array([1, 2])
  b = np.array([3, 4])
  combined = np.concatenate((a, b))
  print(combined)
  # Output: [1 2 3 4]
  ```

- **`np.split()`**: Split an array into multiple sub-arrays.
  ```python
  arr = np.array([0, 1, 2, 3, 4, 5])
  split = np.split(arr, 3)
  print(split)
  # Output: [array([0, 1]), array([2, 3]), array([4, 5])]
  ```

- **`np.mean()`**: Compute the mean of an array.
  ```python
  arr = np.array([1, 2, 3, 4])
  print(np.mean(arr))
  # Output: 2.5
  ```

- **`np.sum()`**: Compute the sum of an array.
  ```python
  arr = np.array([1, 2, 3, 4])
  print(np.sum(arr))
  # Output: 10
  ```

In [3]:
#Let's see one by one
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:

np.zeros((3,3,3),dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [5]:
#np.ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [7]:
5+np.ones((3,6))

array([[6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.]])

In [8]:
#np.empty
# Creates an array of the given shape and type, without initializing entries.
np.empty((6, 6,2))

array([[[ 4.48703503e-087,  1.21861333e-152],
        [ 8.80119450e+223,  7.40954004e-130],
        [ 4.02779965e+241,  9.63937808e-310],
        [ 6.09251832e-242,  6.93972143e+218],
        [ 2.42382356e+188,  7.35869375e+223],
        [-3.38460945e+125,  9.10178554e+097]],

       [[-2.00497879e+190,  4.93247975e-312],
        [ 5.14867557e+025,  4.03438662e-237],
        [ 9.79882228e+252,  1.34661443e+195],
        [ 4.89003983e-312,  6.61822051e+025],
        [ 6.15594962e-242,  4.92595326e+078],
        [ 7.43663306e+096,  1.83190542e+016]],

       [[-3.38460823e+125,  2.99091040e+262],
        [ 7.62951521e-310,  7.68983923e-271],
        [ 2.17518808e+243, -1.04243622e+224],
        [ 5.08101945e-312,  7.49773090e+247],
        [ 7.86946426e+276,  6.25374877e-304],
        [ 8.73990640e+245,  6.01346930e-154]],

       [[-3.38460756e+125,  4.74837995e+170],
        [ 1.68124972e-303, -8.55683934e+016],
        [ 5.97564987e-246, -3.05535169e-115],
        [-3.90577136e-308, -

In [9]:
#np.linspace
# Returns evenly spaced numbers over a specified interval.
# The endpoint is included by default.
np.linspace(2, 6)
#how it works
# The function takes three arguments: start, stop, and num (the number of samples to generate).
# It returns an array of evenly spaced values between the start and stop values.
# The default value for num is 50 if not specified.
np.linspace(2, 6, 3)  # Example with specified number of samples

array([2., 4., 6.])

In [10]:

np.linspace(2,6,10,endpoint=False).reshape(5,2)  # Example with endpoint set to False
np.linspace(2,6,6,retstep=True)

(array([2. , 2.8, 3.6, 4.4, 5.2, 6. ]), np.float64(0.8))

In [11]:
np.logspace(3, 6, 10, endpoint=True ,base=2)

array([ 8.        , 10.0793684 , 12.69920842, 16.        , 20.1587368 ,
       25.39841683, 32.        , 40.3174736 , 50.79683366, 64.        ])

In [12]:
a = np.arange(1, 10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
a.max()

np.int64(9)

In [14]:
a.max(axis=0)  # Maximum value along the first axis (columns)

array([7, 8, 9])

In [15]:
a.max(axis=1)  # Maximum value along the second axis (rows)

array([3, 6, 9])

In [16]:
10+a

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [17]:
a/0

C:\Users\haida\AppData\Local\Temp\ipykernel_15056\4102073204.py:1: RuntimeWarning: divide by zero encountered in divide
  a/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [18]:
a**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [19]:
pow(a, 2)  # Equivalent to a**2, raises each element to the power of 2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [20]:
b = np.array([2,4,1])
b

array([2, 4, 1])

In [21]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [23]:
a.T+b

array([[ 3,  8,  8],
       [ 4,  9,  9],
       [ 5, 10, 10]])

In [24]:
a+b

array([[ 3,  6,  4],
       [ 6,  9,  7],
       [ 9, 12, 10]])

In [25]:
b = b.reshape(1, -1)

b

array([[2, 4, 1]])

In [26]:
a + b.T 

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [ 8,  9, 10]])

In [27]:
np.sqrt(a)  # Square root of each element in the array

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [28]:
np.exp(a)  # Exponential of each element in the array
# Element-wise addition of a and b
# a + b

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [29]:
np.log10(a)  # Base-10 logarithm of each element in the array

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [42]:
import numpy as np
x = np.array([1, 2, 3])


In [48]:
y = x

In [43]:
z = np.copy(x)  # Create a copy of x

In [44]:
x[0] = 100
y

array([100,   2,   3])

In [45]:
z

array([1, 2, 3])

In [50]:
id(x)

2615170334416

In [49]:
id(y)

2615170334416

In [51]:
id(z)

2615170334320

In [57]:
id(y[0])

2615169774480

In [58]:
id(x[0])

2615169776528

In [59]:
id(x[0])==id(y[0])

True

In [109]:
import numpy as np

x = np.array([1, 3, 5])

y = x



In [120]:
print(id(x[0]), id(y[0]))  # may match
print(id(x[0]), id(x[0]))  # may differ, new object each call
print(x[0] == y[0])  

2615170666736 2615170666736
2615170666672 2615170666672
True


In [113]:
id(y[0])

2615170664464

In [121]:
su = np.array([567,345])
df = su
id(su)

2615170779248

In [122]:
id(df)

2615170779248

In [123]:
id(su[0])

2615170666000

In [124]:
id(df[0])

2615170666480

In [131]:

print(id(su[0]))
print(id(df[0]))
print(id(su[1]), id(df[0]))  # may match
print(id(su[0]), id(su[0]))
print(id(su[1]) == id(df[0]))  # Check if the IDs of the first element of su and df are the same

2615170667728
2615170667952
2615170667952 2615170667952
2615170667344 2615170667344
True
