In [53]:

import numpy as np

# NumPy Array Methods and Examples

This notebook demonstrates commonly used NumPy methods for creating, manipulating, and analyzing arrays. Each code cell is accompanied by a markdown explanation for clarity.

In [54]:
l = [1,2,4,45,5,6,6]
arr = np.array(l)
arr

array([ 1,  2,  4, 45,  5,  6,  6])

## Creating a NumPy Array

You can create a NumPy array from a Python list using `np.array()`. This is the foundation for most NumPy operations.

# NumPy Methods
NumPy provides a wide range of methods for performing operations on arrays.
These methods allow for efficient manipulation and computation on large datasets.

Some commonly used NumPy methods include:

- **`np.array()`**: Create a NumPy array.
  ```python
  arr = np.array([1, 2, 3])
  print(arr)
  # Output: [1 2 3]
  ```

- **`np.zeros()`**: Create an array filled with zeros.
  ```python
  zeros = np.zeros((2, 3))
  print(zeros)
  # Output: [[0. 0. 0.]
  #          [0. 0. 0.]]
  ```

- **`np.ones()`**: Create an array filled with ones.
  ```python
  ones = np.ones((2, 3))
  print(ones)
  # Output: [[1. 1. 1.]
  #          [1. 1. 1.]]
  ```

- **`np.arange()`**: Create an array with a range of values.
  ```python
  arr = np.arange(0, 10, 2)
  print(arr)
  # Output: [0 2 4 6 8]
  ```

- **`np.linspace()`**: Create an array with evenly spaced values.
  ```python
  arr = np.linspace(0, 1, 5)
  print(arr)
  # Output: [0.   0.25 0.5  0.75 1.  ]
  ```

- **`np.reshape()`**: Change the shape of an array.
  ```python
  arr = np.arange(6)
  reshaped = arr.reshape((2, 3))
  print(reshaped)
  # Output: [[0 1 2]
  #          [3 4 5]]
  ```

- **`np.concatenate()`**: Join two or more arrays.
  ```python
  a = np.array([1, 2])
  b = np.array([3, 4])
  combined = np.concatenate((a, b))
  print(combined)
  # Output: [1 2 3 4]
  ```

- **`np.split()`**: Split an array into multiple sub-arrays.
  ```python
  arr = np.array([0, 1, 2, 3, 4, 5])
  split = np.split(arr, 3)
  print(split)
  # Output: [array([0, 1]), array([2, 3]), array([4, 5])]
  ```

- **`np.mean()`**: Compute the mean of an array.
  ```python
  arr = np.array([1, 2, 3, 4])
  print(np.mean(arr))
  # Output: 2.5
  ```

- **`np.sum()`**: Compute the sum of an array.
  ```python
  arr = np.array([1, 2, 3, 4])
  print(np.sum(arr))
  # Output: 10
  ```

In [55]:
#Let's see one by one
np.zeros(5)

array([0., 0., 0., 0., 0.])

## np.zeros

`np.zeros()` creates a new array of the given shape and type, filled with zeros. Useful for initializing arrays for further computation.

In [56]:

np.zeros((3,3,3),dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [57]:
#np.ones
np.ones(5)

array([1., 1., 1., 1., 1.])

## np.ones

`np.ones()` creates a new array of the given shape and type, filled with ones. This is useful for initializing arrays where you want all values to start as 1.

In [58]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [59]:
5+np.ones((3,6))

array([[6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.]])

In [60]:
#np.empty
# Creates an array of the given shape and type, without initializing entries.
np.empty((6, 6,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

## np.empty

`np.empty()` creates a new array of the given shape and type, without initializing entries. The values in the array are whatever happens to already exist at that memory location.

In [61]:
#np.linspace
# Returns evenly spaced numbers over a specified interval.
# The endpoint is included by default.
np.linspace(2, 6)
#how it works
# The function takes three arguments: start, stop, and num (the number of samples to generate).
# It returns an array of evenly spaced values between the start and stop values.
# The default value for num is 50 if not specified.
np.linspace(2, 6, 3)  # Example with specified number of samples

array([2., 4., 6.])

## np.linspace

`np.linspace()` returns evenly spaced numbers over a specified interval. Useful for generating sequences of numbers with a specific number of elements.

In [62]:

np.linspace(2,6,10,endpoint=False).reshape(5,2)  # Example with endpoint set to False
np.linspace(2,6,6,retstep=True)

(array([2. , 2.8, 3.6, 4.4, 5.2, 6. ]), np.float64(0.8))

In [63]:
np.logspace(3, 6, 10, endpoint=True ,base=2)

array([ 8.        , 10.0793684 , 12.69920842, 16.        , 20.1587368 ,
       25.39841683, 32.        , 40.3174736 , 50.79683366, 64.        ])

In [64]:
a = np.arange(1, 10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## np.arange and np.reshape

- `np.arange()` creates an array with a range of values, similar to Python's built-in range but returns a NumPy array.
- `np.reshape()` changes the shape of an array without changing its data.

In [65]:
a.max()

np.int64(9)

## np.max and axis argument

- `np.max()` or `array.max()` returns the maximum value in the array.
- The `axis` argument specifies whether to compute the maximum across rows or columns.

In [66]:
a.max(axis=0)  # Maximum value along the first axis (columns)

array([7, 8, 9])

In [67]:
a.max(axis=1)  # Maximum value along the second axis (rows)

array([3, 6, 9])

In [68]:
10+a

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

## Broadcasting in NumPy

Broadcasting allows NumPy to perform arithmetic operations on arrays of different shapes. For example, adding a scalar to an array adds that value to every element.

In [69]:
a/0

C:\Users\haida\AppData\Local\Temp\ipykernel_14444\4102073204.py:1: RuntimeWarning: divide by zero encountered in divide
  a/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [70]:
a**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

## Element-wise Operations

NumPy supports element-wise operations, such as squaring every element in an array using `**` or functions like `np.sqrt()` and `np.exp()`.

In [71]:
pow(a, 2)  # Equivalent to a**2, raises each element to the power of 2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [72]:
b = np.array([2,4,1])
b

array([2, 4, 1])

In [73]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [75]:
a.T+b

array([[ 3,  8,  8],
       [ 4,  9,  9],
       [ 5, 10, 10]])

In [76]:
a+b

array([[ 3,  6,  4],
       [ 6,  9,  7],
       [ 9, 12, 10]])

In [77]:
b = b.reshape(1, -1)

b

array([[2, 4, 1]])

In [78]:
a + b.T 

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [ 8,  9, 10]])

In [79]:
np.sqrt(a)  # Square root of each element in the array

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [80]:
np.exp(a)  # Exponential of each element in the array
# Element-wise addition of a and b
# a + b

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [81]:
np.log10(a)  # Base-10 logarithm of each element in the array

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [82]:
import numpy as np
x = np.array([1, 2, 3])


In [83]:
y = x

In [84]:
z = np.copy(x)  # Create a copy of x

In [85]:
x[0] = 100
y

array([100,   2,   3])

In [86]:
z

array([1, 2, 3])

In [87]:
id(x)

2530045571120

In [88]:
id(y)

2530045571120

In [89]:
id(z)

2530045570640

In [90]:
id(y[0])

2530045514544

In [91]:
id(x[0])

2530045514256

In [92]:
id(x[0])==id(y[0])

True

In [93]:
import numpy as np

x = np.array([1, 3, 5])

y = x



In [94]:
print(id(x[0]), id(y[0]))  # may match
print(id(x[0]), id(x[0]))  # may differ, new object each call
print(x[0] == y[0])  

2530045514480 2530045514480
2530045510160 2530045510160
True


In [95]:
id(y[0])

2530045514544

In [96]:
su = np.array([567,345])
df = su
id(su)

2530045572752

In [97]:
id(df)

2530045572752

In [98]:
id(su[0])

2530045514480

In [99]:
id(df[0])

2530045514480

In [100]:

print(id(su[0]))
print(id(df[0]))
print(id(su[1]), id(df[0]))  # may match
print(id(su[0]), id(su[0]))
print(id(su[1]) == id(df[0]))  # Check if the IDs of the first element of su and df are the same

2530045514480
2530045515184
2530045515184 2530045515184
2530045512016 2530045512016
True
